### ISSUE TITLE
BCE Loss

### ISSUE THREAD

**Issue by alexrame** [chandar-lab/PatchUp#2]
Hello
Thank you for the nice work.
I have one question related to the loss.
When reading your paper, I could not figure out the difference between the 2 losses. Indeed,  CutMix has the same loss than MixUp: it is equivalent to do the weighting by "lambda" after or after the categorical cross entropy.
Then I read your code and realized that you are using a binary cross entropy (nn.BCELoss). In this case, the 2 losses are indeed different.
Could you explain why you used this binary cross entropy ?
Thanks in advance

**Comment by JingLiJJ** [comment]
I'm curious about this question too. Have you figured this out?

**Comment by alexrame** [comment]
No, but I guess this issue is deeper than what I first thought

**Comment by JingLiJJ** [comment]
Could you tell me why use BCELoss, the 2 losses are different? I think they are the same as well.
