### ISSUE TITLE
Layer at which PatchUp is applied

### ISSUE THREAD

**Issue by rahulvigneswaran** [chandar-lab/PatchUp#9]
In the paper it is mentioned that the block `k` for applying the PatchUp is selected at random. I believe this part is implemented in the following line,
https://github.com/chandar-lab/PatchUp/blob/31133f358c2b59536eeb5ef304acec2b1436ec23/models/preresnet.py#L140

My question here is the default value for `args.k` is set to `2` and it was not altered at all in the running information provided in the `README.md`. Is there any reason behind this or was the `k` simply set to the maximum block count in each network during your runs?

@bemova

**Comment by bemova** [comment]
It is based on the hyperparameter search that we did in our setup. ManifoldMixup also set it to 2. So it makes the comparison fair with ManifoldMixup. 
You can try more blocks using --k argument when you run main.py.
